name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: "23.5.0"
  PACKAGE_MANAGER: "npm"
  PATH: "./ai-portfolio"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check lockfiles
        shell: "bash"
        working-directory: ${{ PATH }}
        env:
          INPUT_PM: ${{ PACKAGE_MANAGER }}
        run: |
          len=`echo $INPUT_PM | wc -c`
          if [ $len -gt 1 ]; then
            PACKAGE_MANAGER=$(echo "$INPUT_PM" | grep -o '^[^@]*')
            VERSION=$(echo "$INPUT_PM" | { grep -o '@.*' || true; } | sed 's/^@//')
            # Set default VERSION if not provided
            if [ -z "$VERSION" ]; then
                VERSION="latest"
            fi
            echo "PACKAGE_MANAGER=$PACKAGE_MANAGER" >> $GITHUB_ENV
          elif [ $(find "." -maxdepth 1 -name "pnpm-lock.yaml") ]; then
              echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
              echo "LOCKFILE=pnpm-lock.yaml" >> $GITHUB_ENV
          elif [ $(find "." -maxdepth 1 -name "yarn.lock") ]; then
              echo "PACKAGE_MANAGER=yarn" >> $GITHUB_ENV
              echo "LOCKFILE=yarn.lock" >> $GITHUB_ENV
          elif [ $(find "." -maxdepth 1 -name "package-lock.json") ]; then
              VERSION="latest"
              echo "PACKAGE_MANAGER=npm" >> $GITHUB_ENV
              echo "LOCKFILE=package-lock.json" >> $GITHUB_ENV
          elif [ $(find "." -maxdepth 1 -name "bun.lock") ]; then
              VERSION="latest"
              echo "PACKAGE_MANAGER=bun" >> $GITHUB_ENV
              echo "LOCKFILE=bun.lock" >> $GITHUB_ENV
          elif [ $(find "." -maxdepth 1 -name "bun.lockb") ]; then
              VERSION="latest"
              echo "PACKAGE_MANAGER=bun" >> $GITHUB_ENV
              echo "LOCKFILE=bun.lockb" >> $GITHUB_ENV
          else
              echo "No lockfile found.
          Please specify your preferred \"package-manager\" in the action configuration."
              exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup PNPM
        if: ${{ env.PACKAGE_MANAGER == 'pnpm' }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.VERSION }}
          package_json_file: "${{ PATH }}/package.json"

      - name: Setup Bun
        if: ${{ env.PACKAGE_MANAGER == 'bun' }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ env.PACKAGE_MANAGER != 'bun' }}
        with:
          node-version: ${{ NODE_VERSION}}
          cache: ${{ env.PACKAGE_MANAGER }}
          cache-dependency-path: "${{ PATH }}/${{ env.LOCKFILE }}"

      - name: Setup Node (Bun)
        uses: actions/setup-node@v4
        if: ${{ env.PACKAGE_MANAGER == 'bun' }}
        with:
          node-version: ${{ NODE_VERSION }}

      - name: Install
        shell: "bash"
        working-directory: ${{ PATH }}
        run: $PACKAGE_MANAGER install

      - name: Build
        shell: "bash"
        working-directory: ${{ PATH }}
        run: $PACKAGE_MANAGER run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
